### ISSUE TITLE
"kiggelærer" cant copy activity

### ISSUE THREAD

**Issue by Mikkeljeppesen1** [praxisdigital/moodle-block_sharing_cart#100]
On niels brock and kvuc:

If you have only the "kiggelærer" role, you cant copy activities. If you have the "lærer" role, you can. Frederik says the capability is correct on niels brock.

**Comment by AraPraxis** [comment]
As we've stated in previous sharing cart issues (On donhinkelman's repo) this will be fixed in the MOODLE_41_STABLE & master (a 42 stable will also be created)
We tend to follow Moodle's bug fix "timeline", which has been ecxeeded in 4.0



![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/89771146/1bd6e3ec-9770-4fad-b44d-ae59a0487af6)
