### ISSUE TITLE
Error in copying URL to sharing cart

### ISSUE THREAD

**Issue by neeesn** [praxisdigital/moodle-block_sharing_cart#123]
On nielsbrock the have an URL activity, that links to an PDF on dr.dk. That activity cant be copied to the sharing cart. It just stands there running: https://www.loom.com/share/f115f647bf814c7aa5b2bf36f8f71b3c

https://www.mitnielsbrock.dk/course/view.php?id=60041&section=13

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/1931926/1c7cfb87-715b-4761-b67d-9e31cb2e2480)

after 10 minutes or so this error is shown: 

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/1931926/84544908-c1be-45db-ab5f-7aa9d20098a1)

Hubspot: https://app-eu1.hubspot.com/contacts/25645903/record/0-5/2038978767

**Comment by frederikmillingpytlick** [comment]
The course https://www.mitnielsbrock.dk/course/view.php?id=60041 has 180.000 badges. That's why the backup is taking so long and eventually times out. If given enough time, it probably would succeed.

If you backup the module using Moodle Core and select everything it also times out. Leaving out the badges works.

Has the duplication of badges error been reintroduced into Moodle core?

**Comment by frederikmillingpytlick** [comment]
Awaiting customer, whether we are allowed to delete the duplicate badges.

**Comment by frederikmillingpytlick** [comment]
Customer gave OK, executing cli script

**Comment by frederikmillingpytlick** [comment]
@neeesn 

The 2.6 million duplicate badges have now been deleted and it works like a charm.

There are 10.000 remaining badges
