### ISSUE TITLE
Errors when copying to or from Sharing Cart

### ISSUE THREAD

**Issue by superfoght** [praxisdigital/moodle-block_sharing_cart#132]
For example on this course: 

https://www.mitnielsbrock.dk/course/view.php?id=52901&section=28

![Image](https://github.com/praxisdigital/moodle-block_sharing_cart/assets/2778015/d88b8082-8cbf-4400-83b7-5ec1e10b0c15)

https://app-eu1.hubspot.com/contacts/25645903/record/0-5/2526221267

And on ipraxis: 
https://master.praxis.dk/course/view.php?id=47395#section-29

I tried to both copy the entire section: Uge 13 (25/3-31/3): Selvrettende opgaver 3

and just a question: 
SMS'er (sæt dialog i rækkefølge - cafe, bio, invitation) 0,5 lektion

I worked fine if I just copied the H5P activity.

**Comment by mcardle** [comment]
We can't really say what the reason was, but it was solved by allocating more resources to the site. We continuously work to reduce the consumption of resources so that sites run better and more stably. We have recently switched to GitOps, where there were some settings that had to be set again, for customers with large sites.
