### ISSUE TITLE
block_sharing_cart issue #155

### ISSUE THREAD

**Issue by Snowdle** [praxisdigital/moodle-block_sharing_cart#84]
Requires further investigation. 

https://github.com/donhinkelman/moodle-block_sharing_cart/issues/155

**Comment by AraPraxis** [comment]
I've asked them to try and pull a newer release of Sharing cart, since we've had a similar issue (https://github.com/donhinkelman/moodle-block_sharing_cart/issues/118)
By giselebrugger's information she's using Moodle 4.0 Release 2 and  Release 3 should hopefully fixing their problem - If not, then we'll investigate further

**Comment by AraPraxis** [comment]
They pulled a newer release and their problem got fixed.
Closing issue.
